### PR TITLE
docs: adds guide to pull vesting information

### PR DESCRIPTION
**Pull request by smol-ninja**
Closes https://github.com/sablier-labs/docs/issues/188.

[Preview here](https://v2-docs-gap6dctxs-sablier.vercel.app/guides/lockup/examples/vesting-data).

### CODE REVIEW

**Comment by PaulRBerg** [comment]
Great work @smol-ninja!!

I suppose that the Linear vs Dynamic vs Tranched section will have to updated after the V2.0.0 merger.

**Comment by smol-ninja** [comment]
Yeah. It will be a huge refactor of doc for v2.0.0

**Comment by PaulRBerg** [comment]
FYI, I am doing one final review cycle and will push a commit shortly

Then I'll merge

**Comment by smol-ninja** [comment]
Thanks for polishing the guide @PaulRBerg. Looks much better now.

**Pull request merged**
