### PR TITLE
chore: img png to webp

### PR DESCRIPTION
**Pull request by tukwan**
Optimising images and solving `Image file size too large` on Ahrefs page audit. 

Part of:  https://github.com/sablier-labs/v2-interfaces/pull/1202

### CODE REVIEW

**Comment by PaulRBerg** [comment]
Thanks @tukwan, the PR itself looks good to me, but I wonder if we couldn't just keep the PNG images as is, and use this plugin instead?

Could you look into it, please?

https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-ideal-image

**Comment by tukwan** [comment]
I’ve looked into this plugin and played a bit [here](https://github.com/sablier-labs/docs/compare/chore/img-optimize?expand=1), and it has quite a few issues and limitations:

1. **PNG to WebP**: It’s not converting PNG to WebP, which means it’s losing more quality by only compressing PNG instead of properly optimizing them with the newest version of [sharp](https://github.com/lovell/sharp) as we do it [here](https://github.com/sablier-labs/v2-interfaces/blob/main/packages/utils/src/scripts/optimus.js).

2. **Flashing**: There are some unresolved bugs, like image flashing ([GitHub Issue #10214](https://github.com/facebook/docusaurus/issues/10214#issuecomment-2239443286)). 

Also from the maintainer of Docusaurus:
> The plugin itself seems pretty old and is described as hard to maintain and reason about.

3. **Image Wrapping**: It’s wrapping images with a parent div, width and height don't work. Fixing this would require writing even more custom code to get things working as expected ([GitHub Issue #8452](https://github.com/facebook/docusaurus/issues/8452#issuecomment-1354685716)).
x 1

Overall, this plugin feels outdated and buggy, and solving these problems might end up being more effort than it’s worth.

**Comment by PaulRBerg** [comment]
Great, thanks for looking into it!

**Comment by tukwan** [comment]
@smol-ninja this script [here](https://github.com/sablier-labs/v2-interfaces/blob/main/packages/utils/src/scripts/optimus.js)

**Pull request merged**
