### PR TITLE
docs: custom deployment guide

### PR DESCRIPTION
**Pull request by PaulRBerg**
Closes https://github.com/sablier-labs/docs/issues/173.

cc @smol-ninja and @andreivladbrg — could you lend me a hand here?

I am not up to speed with the latest way in which we make deployments nowadays.

I suppose we might need to open source the Warp Drive scripts? If yes, let's put them in the [GitHub Wiki](https://github.com/sablier-labs/v2-core/wiki/Deployments).

### CODE REVIEW

**Comment by smol-ninja** [comment]
On it.

**Comment by smol-ninja** [comment]
I've updated the PR. Anyone who follows the guidelines should be able to make a deployment with minimalistic efforts—by simple copy-pasting the commands from the doc. I've personally followed the guide to make new testnet deployments just now.

> I suppose we might need to open source the Warp Drive scripts

I have added the commands in the doc itself. We may not need to open source the warp scripts. Have a look and let me know what you think.

Should I also update [GitHub Wiki](https://github.com/sablier-labs/v2-core/wiki/Deployments) to match the content from the docs's [Deployment Guide](https://v2-docs-t6umhqmj6-sablier.vercel.app/contracts/v2/guides/custom-deployments#deployment-guide)?

**Comment by PaulRBerg** [comment]
Thanks @smol-ninja, great work. I pushed a commit to polish a few things.

About the GitHub Wiki — let's deprecate it in favor of this new section in the docs. Can you edit it to say something like "The deployments guide have been moved to our documentation site"?

The goal with open-sourcing the Warp Drive scripts was to avoid duplicating the scripts between the docs site and Warp. But I guess having to synchronize the Warp Drive scripts to a GitHub repo or something is itself a form of overhead.

**Comment by PaulRBerg** [comment]
I will merge later today

**Comment by smol-ninja** [comment]
I've updated the deployment wiki page: https://github.com/sablier-labs/v2-core/wiki/Deployments

**Pull request merged**
